config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'static#about'

  get '/contact', to: 'static#contact'

  get '/rules', to: 'static#rules'

  get '/rules/ShowMeCompRules', to: 'static#get_rules'

  get '/rules/ShowMeRulesEvidence', to: 'static#get_rules_evidence'

  get '/rules/highlights', to: 'static#rule_highlights'

  get '/case', to: 'static#case'

  get '/case/download', to: 'static#get_case'
  
  get '/schedule', to: 'static#schedule'

  get '/location', to: 'static#location'

  get '/deadlines', to: 'static#deadlines'
  
  get '/ballot', to: 'static#get_ballot'

  get '/comments', to: 'static#get_guidelines'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post '/pay_registration', to: 'sessions#pay_registration'

  delete '/delete', to: 'sessions#delete'

  get '/profile', to: 'sessions#profile'

  get '/list', to: 'sessions#list'

  get '/teams', to: 'sessions#teams'

  get '/teams/rankings', to: 'teams#rankings'

  get '/teams/:id/edit', to: 'teams#edit'

  delete '/students/:id/delete', to: 'students#delete'

  get '/students/rankings', to: 'students#rankings'

  post '/teams/:id/edit', to: 'teams#addStudent'

  get '/resend', to: 'sessions#resend'

  get '/trials/schedule', to: 'trials#new'

  post '/trials/schedule', to: 'trials#create'

  get '/trials/list', to: 'trials#schedule'

  get '/trials/:id/score', to: 'trials#score_form'

  post '/trials/:id/score', to: 'trials#score'

  root 'static#home'

  resources :users

  resources :teams, only: [:delete]

  resources :activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :validate_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by_email(params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Password Reset requested. Please check your email for instructions on resetting your password."
      redirect_to root_url
    else
      flash[:danger] = "Email not found. If you believe this is an error, please email us at showmemocktrial@gmail.com"
      redirect_to root_url
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      login @user
      flash[:success] = "Password has been updatesd."
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  private
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = 'Error: This link has expired.'
        redirect_to new_password_reset_url
      end
    end

    def get_user
      @user = User.find_by_email(params[:email])
    end
    
    def validate_user
      unless(
        @user&.activated? && @user.authenticated?(:reset, params[:id])) 
        redirect_to root_url
      end
    end

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1 class="title-panel container">Password Reset</h1>
<div class="content-panel container">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
            <%= render 'shared/errors' %>

            <%= hidden_field_tag :email, @user.email %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :confirm_password, "Password Confirmation" %>
            <%= f.password_field :confirm_password, class: 'form-control' %>

            <%= f.submit "Update Password", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:page_title, "Password Reset") %>

<h1 class="title-panel container">Password Reset</h1>

<div class="content-panel container">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:password_reset, url: password_resets_path) do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>