config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'static#about'

  get '/contact', to: 'static#contact'

  get '/rules', to: 'static#rules'

  get '/rules/ShowMeCompRules', to: 'static#get_rules'

  get '/rules/ShowMeRulesEvidence', to: 'static#get_rules_evidence'

  get '/rules/highlights', to: 'static#rule_highlights'

  get '/case', to: 'static#case'

  get '/case/download', to: 'static#get_case'
  
  get '/schedule', to: 'static#schedule'

  get '/location', to: 'static#location'

  get '/deadlines', to: 'static#deadlines'
  
  get '/ballot', to: 'static#get_ballot'

  get '/comments', to: 'static#get_guidelines'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post '/pay_registration', to: 'sessions#pay_registration'

  delete '/delete', to: 'sessions#delete'

  get '/profile', to: 'sessions#profile'

  get '/list', to: 'sessions#list'

  get '/teams', to: 'sessions#teams'

  get '/teams/rankings', to: 'teams#rankings'

  get '/teams/:id/edit', to: 'teams#edit'

  delete '/students/:id/delete', to: 'students#delete'

  get '/students/rankings', to: 'students#rankings'

  post '/teams/:id/edit', to: 'teams#addStudent'

  get '/resend', to: 'sessions#resend'

  get '/trials/schedule', to: 'trials#new'

  post '/trials/schedule', to: 'trials#create'

  get '/trials/list', to: 'trials#schedule'

  get '/trials/:id/score', to: 'trials#score_form'

  post '/trials/:id/score', to: 'trials#score'

  root 'static#home'

  resources :users

  resources :teams, only: [:delete]

  resources :activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_header.html.erb
<header class='navbar navbar-expand flex-column flex-md-row bd-navbar' style='z-index: 1000'>
	<nav>
  		<div class="navbar-nav-scroll">
  			<ul class="nav navbar-nav flex-row">
  				<li><%= link_to "Home", root_path, class: 'nav-link' %></li>
  				<li class="dropdown">
            <%= link_to "About", about_path, class: 'nav-link' %>
            <ul class='nav flex-column'>
              <li><%= link_to "Info", about_path, class: 'dropdown-content nav-link' %></li>
              <li><%= link_to "Schedule", schedule_path, class: 'dropdown-content nav-link' %></li>
              <li><%= link_to "Location", location_path, class: 'dropdown-content nav-link' %></li>
              <li><%= link_to "Deadlines", deadlines_path, class: 'dropdown-content nav-link' %></li>
            </ul>
          </li>
  				<li><%= link_to "Contact", contact_path, class: 'nav-link' %></li>
          <li><%= link_to "Rules", rules_path, class: 'nav-link' %></li>
          <li><%= link_to "Case Materials", case_path, class: 'nav-link' %></li>

          <% if current_user&.admin? %>
            <li><%= link_to "Coaches", list_path, class: 'nav-link' %></li>
            <li><%= link_to "Trials", trials_list_path, class: 'nav-link' %></li>
            <li><%= link_to "Student Rankings", students_rankings_path, class: 'nav-link' %></li>
          <% end %>

          <% if !logged_in? %>
            <li><%= link_to "Login", login_path, class: 'nav-link' %></li>
            <li><%= link_to "Register Now!", signup_path, class: 'signup-button nav-link' %></li>
          <% else %>
            <li><%= link_to "Profile", profile_path, class: 'nav-link' %></li>
            <li><%= link_to "Logout", logout_path, method: :delete, class: 'nav-link' %></li>
          <% end %>
        </ul>
  		</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url('<%= bg_image(yield(:page_title).downcase) %>');">

  	<%= render 'layouts/shim' %>
  	<%= render 'layouts/header' %>
    <%= render 'shared/flash' %>

    <div class="container-fluid">
  		<%= yield %>
  	</div>
    
    <%= debug(params) if Rails.env.test? %>
    
  </body>
</html>